[build]
target = "armv7-unknown-linux-uclibceabihf"

[target.armv7-unknown-linux-uclibceabihf]
linker = "/home/christian/luckfox/luckfox-pico/sysdrv/source/buildroot/buildroot-2023.02.6/output/host/bin/arm-buildroot-linux-uclibcgnueabihf-gcc"
